### PR TITLE
fix(scroll-area): fixed missing key prop error

### LINKED ISSUE #1294: Scroll-Area: Missing "key" prop for element in iterator
I found the `ScrollArea` Component with this error:

error shadui

### PR DESCRIPTION
**Pull request by SoyDiego**
Fix #1294

I applied the same way used in `apps/www/registry/new-york/example/scroll-area-demo.tsx` removing the `React.Fragment`and added the `key`.

## CURRENT
error shadui

## AFTER SOLUTION
fixed shadui

### CODE REVIEW

File: apps/www/registry/new-york/example/scroll-area-demo.tsx [hunk 1]
```diff
@@ -14,7 +14,9 @@ export default function ScrollAreaDemo() {
         <h4 className="mb-4 text-sm font-medium leading-none">Tags</h4>
         {tags.map((tag) => (
           <>
-            <div className="text-sm">{tag}</div>
+            <div className="text-sm" key={tag}>
```
Comment (shadcn) [inline apps/www/registry/new-york/example/scroll-area-demo.tsx:17]: Nit: can we put the key as the first prop for consistency? Thank you.

Comment (SoyDiego) [reply apps/www/registry/new-york/example/scroll-area-demo.tsx]: Done @shadcn, thanks.
I moved the prop key as the first prop in New York too.

This are my first commits and PR's here. If something is not ok, let me know :)

Thanks!

**Review by shadcn — APPROVED** [review]
Thank you.
